"""
Management command to import SAT questions.
Includes questions across all difficulty levels (easy, medium, hard) and
all subjects (Math, Reading and Writing).
"""

from django.core.management.base import BaseCommand

from questions.models import Question

QUESTIONS_DATA = [
    # ==================== EASY QUESTIONS ====================
    # Easy Math - Algebra
    {
        "question_id": "easy_math_001",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear equations in one variable",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "If 5x + 10 = 35, what is the value of x?",
        "choice_a": "3",
        "choice_b": "5",
        "choice_c": "7",
        "choice_d": "9",
        "correct_answer": "B",
        "explanation": "Subtract 10 from both sides: 5x = 25. Then divide both sides by 5: x = 5. You can verify by substituting: 5(5) + 10 = 25 + 10 = 35 ✓",
    },
    {
        "question_id": "easy_math_002",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear functions",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "The function f is defined by f(x) = 3x - 7. What is the value of f(5)?",
        "choice_a": "-2",
        "choice_b": "2",
        "choice_c": "8",
        "choice_d": "22",
        "correct_answer": "C",
        "explanation": "Substitute x = 5 into the function: f(5) = 3(5) - 7 = 15 - 7 = 8.",
    },
    {
        "question_id": "easy_math_003",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Problem-Solving and Data Analysis",
        "skill": "Percentages",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "A shirt originally costs $40. If it is on sale for 25% off, what is the sale price?",
        "choice_a": "$10",
        "choice_b": "$15",
        "choice_c": "$30",
        "choice_d": "$35",
        "correct_answer": "C",
        "explanation": "Calculate 25% of $40: 0.25 × 40 = $10. Subtract from original: $40 - $10 = $30. Alternatively, 75% of $40 = 0.75 × 40 = $30.",
    },
    {
        "question_id": "easy_math_004",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear equations in one variable",
        "difficulty": "easy",
        "question_type": "free_response",
        "question_text": "If 4x - 8 = 20, what is the value of x?",
        "correct_answer": "7",
        "explanation": "Add 8 to both sides: 4x = 28. Divide by 4: x = 7. Verify: 4(7) - 8 = 28 - 8 = 20 ✓",
    },
    {
        "question_id": "easy_math_005",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear functions",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "The function g is defined by g(x) = 2x + 5. What is the value of g(0)?",
        "choice_a": "0",
        "choice_b": "2",
        "choice_c": "5",
        "choice_d": "7",
        "correct_answer": "C",
        "explanation": "Substitute x = 0 into g(x): g(0) = 2(0) + 5 = 0 + 5 = 5.",
    },
    {
        "question_id": "easy_math_006",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear equations in two variables",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "Line m passes through the origin and has a slope of 3. Which equation represents line m?",
        "choice_a": "y = 3",
        "choice_b": "y = x + 3",
        "choice_c": "y = 3x",
        "choice_d": "y = 3x + 1",
        "correct_answer": "C",
        "explanation": "A line through the origin has y-intercept 0. With slope 3, the equation is y = mx + b = 3x + 0 = 3x.",
    },
    # Easy Reading
    {
        "question_id": "easy_read_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Information and Ideas",
        "skill": "Central ideas and details",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "passage": "The honeybee performs a unique dance to communicate the location of food sources to other bees in the hive. By moving in a figure-eight pattern and waggling its body, the bee can indicate both the direction and distance of flowers relative to the sun's position.",
        "question_text": "According to the passage, how do honeybees communicate the location of food?",
        "choice_a": "Through high-pitched sounds",
        "choice_b": "By releasing chemical signals",
        "choice_c": "Through a specific dance pattern",
        "choice_d": "By flying in circles around the hive",
        "correct_answer": "C",
        "explanation": "The passage explicitly states that honeybees perform 'a unique dance' involving a 'figure-eight pattern' and body waggling to communicate food locations. This directly supports answer C.",
    },
    {
        "question_id": "easy_read_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Information and Ideas",
        "skill": "Central ideas and details",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "passage": "Mount Everest, standing at 29,032 feet, is the highest point on Earth above sea level. However, if measured from base to summit, Mauna Kea in Hawaii is actually taller, with much of its height hidden beneath the ocean surface.",
        "question_text": "What does the passage suggest about measuring mountain height?",
        "choice_a": "All mountains should be measured from sea level",
        "choice_b": "Different measurement methods can yield different results",
        "choice_c": "Underwater mountains are always taller",
        "choice_d": "Mount Everest is shrinking over time",
        "correct_answer": "B",
        "explanation": "The passage contrasts two ways of measuring: 'above sea level' (Everest wins) versus 'base to summit' (Mauna Kea wins). This demonstrates that different measurement methods produce different results.",
    },
    # Easy Writing
    {
        "question_id": "easy_write_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Standard English Conventions",
        "skill": "Subject-verb agreement",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": 'Select the option that correctly completes the sentence: "The group of students _____ working on their project."',
        "choice_a": "is",
        "choice_b": "are",
        "choice_c": "were",
        "choice_d": "be",
        "correct_answer": "A",
        "explanation": "The subject is 'group' (singular), not 'students.' A collective noun like 'group' takes a singular verb. Therefore, 'is' is correct.",
    },
    {
        "question_id": "easy_write_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Standard English Conventions",
        "skill": "Punctuation",
        "difficulty": "easy",
        "question_type": "multiple_choice",
        "question_text": "Which sentence uses punctuation correctly?",
        "choice_a": "The three primary colors are: red, blue, and yellow.",
        "choice_b": "The three primary colors are red, blue, and yellow.",
        "choice_c": "The three primary colors are red blue and yellow.",
        "choice_d": "The three, primary colors are red blue and yellow.",
        "correct_answer": "B",
        "explanation": "A colon after 'are' is incorrect because the sentence flows naturally without it. Items in a series need commas. Option B correctly uses commas to separate the three colors.",
    },
    # ==================== MEDIUM QUESTIONS ====================
    # Medium Math - Algebra
    {
        "question_id": "med_math_001",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Systems of two linear equations in two variables",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "If 2x + 3y = 13 and x - y = 1, what is the value of x?",
        "choice_a": "2",
        "choice_b": "3",
        "choice_c": "3.2",
        "choice_d": "4",
        "correct_answer": "C",
        "explanation": "From the second equation: x = y + 1. Substitute into the first: 2(y + 1) + 3y = 13 → 2y + 2 + 3y = 13 → 5y = 11 → y = 2.2. Therefore, x = 2.2 + 1 = 3.2.",
    },
    {
        "question_id": "med_math_002",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Quadratic equations",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "What are the solutions to the equation x² - 5x + 6 = 0?",
        "choice_a": "x = 1 and x = 6",
        "choice_b": "x = 2 and x = 3",
        "choice_c": "x = -2 and x = -3",
        "choice_d": "x = 5 and x = 1",
        "correct_answer": "B",
        "explanation": "Factor the quadratic: x² - 5x + 6 = (x - 2)(x - 3) = 0. Setting each factor to zero: x - 2 = 0 gives x = 2, and x - 3 = 0 gives x = 3.",
    },
    {
        "question_id": "med_math_003",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Geometry and Trigonometry",
        "skill": "Circles",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "A circle in the xy-plane has center (3, -2) and radius 5. Which of the following is the equation of the circle?",
        "choice_a": "(x - 3)² + (y + 2)² = 25",
        "choice_b": "(x + 3)² + (y - 2)² = 25",
        "choice_c": "(x - 3)² + (y + 2)² = 5",
        "choice_d": "(x + 3)² + (y + 2)² = 25",
        "correct_answer": "A",
        "explanation": "The standard form of a circle equation is (x - h)² + (y - k)² = r², where (h, k) is the center and r is the radius. With center (3, -2) and r = 5: (x - 3)² + (y - (-2))² = 5², which simplifies to (x - 3)² + (y + 2)² = 25.",
    },
    {
        "question_id": "med_math_004",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Problem-Solving and Data Analysis",
        "skill": "Ratios, rates, proportional relationships, and units",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "In a class, the ratio of boys to girls is 3:5. If there are 24 students in total, how many girls are in the class?",
        "choice_a": "9",
        "choice_b": "12",
        "choice_c": "15",
        "choice_d": "18",
        "correct_answer": "C",
        "explanation": "The ratio 3:5 means for every 8 parts (3+5), 5 parts are girls. With 24 students: 24 ÷ 8 = 3 students per part. Girls = 5 × 3 = 15.",
    },
    {
        "question_id": "med_math_005",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Equivalent expressions",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "Which of the following is equivalent to (x + 3)(x - 2)?",
        "choice_a": "x² + x - 6",
        "choice_b": "x² - x - 6",
        "choice_c": "x² + 5x - 6",
        "choice_d": "x² - 5x + 6",
        "correct_answer": "A",
        "explanation": "Use FOIL: (x + 3)(x - 2) = x² - 2x + 3x - 6 = x² + x - 6.",
    },
    {
        "question_id": "med_math_006",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Algebra",
        "skill": "Linear inequalities in one or two variables",
        "difficulty": "medium",
        "question_type": "free_response",
        "question_text": "If 3x - 7 > 14, what is the smallest integer value of x that satisfies the inequality?",
        "correct_answer": "8",
        "explanation": "Add 7 to both sides: 3x > 21. Divide by 3: x > 7. The smallest integer greater than 7 is 8.",
    },
    # Medium Reading
    {
        "question_id": "med_read_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Craft and Structure",
        "skill": "Words in context",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "passage": "The scientist's hypothesis, though initially met with skepticism by her peers, was ultimately vindicated when subsequent experiments confirmed her predictions. Her persistence in the face of doubt proved essential to this breakthrough.",
        "question_text": 'As used in the passage, "vindicated" most nearly means:',
        "choice_a": "questioned",
        "choice_b": "proven correct",
        "choice_c": "abandoned",
        "choice_d": "modified",
        "correct_answer": "B",
        "explanation": "Context clues show that 'experiments confirmed her predictions,' indicating the hypothesis was proven right. 'Vindicated' means justified or proven correct, especially after being doubted.",
    },
    {
        "question_id": "med_read_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Information and Ideas",
        "skill": "Command of evidence",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "passage": "The Industrial Revolution transformed not only manufacturing processes but also the social fabric of society. Workers migrated from rural areas to cities in search of employment, leading to rapid urbanization. While factories increased productivity, they also created new challenges including poor working conditions and child labor.",
        "question_text": "Which statement best describes the author's perspective on the Industrial Revolution?",
        "choice_a": "It was entirely beneficial to society",
        "choice_b": "It was a disaster that should have been prevented",
        "choice_c": "It brought both progress and new problems",
        "choice_d": "It primarily affected rural communities",
        "correct_answer": "C",
        "explanation": "The passage presents a balanced view: positive effects ('increased productivity,' 'transformed manufacturing') alongside negative ones ('poor working conditions,' 'child labor'). This balanced presentation suggests the author sees both progress and problems.",
    },
    # Medium Writing
    {
        "question_id": "med_write_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": 'Choose the best transition to complete the sentence: "The experiment yielded unexpected results. _____, the researchers decided to modify their approach."',
        "choice_a": "Nevertheless",
        "choice_b": "Consequently",
        "choice_c": "Similarly",
        "choice_d": "Meanwhile",
        "correct_answer": "B",
        "explanation": "'Consequently' indicates cause and effect: unexpected results led to (caused) the modification. 'Nevertheless' suggests contrast, 'Similarly' suggests comparison, and 'Meanwhile' indicates simultaneous events—none fit the logical relationship here.",
    },
    {
        "question_id": "med_write_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Standard English Conventions",
        "skill": "Form, structure, and sense",
        "difficulty": "medium",
        "question_type": "multiple_choice",
        "question_text": "Which sentence correctly uses pronouns?",
        "choice_a": "Every student must submit their homework on time.",
        "choice_b": "Every student must submit his or her homework on time.",
        "choice_c": "Every student must submit its homework on time.",
        "choice_d": "Every students must submit their homework on time.",
        "correct_answer": "B",
        "explanation": "In formal writing, 'every student' (singular) traditionally requires a singular pronoun. 'His or her' maintains agreement. Note: Modern usage increasingly accepts 'their' as singular (option A), but B is the most traditionally correct for SAT purposes.",
    },
    # ==================== HARD QUESTIONS ====================
    # Hard Math - Advanced
    {
        "question_id": "hard_math_001",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Equivalent expressions",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "If f(x) = x³ - 4x² + x - 4, which of the following is a factor of f(x)?",
        "choice_a": "(x - 1)",
        "choice_b": "(x + 1)",
        "choice_c": "(x - 4)",
        "choice_d": "(x + 4)",
        "correct_answer": "C",
        "explanation": "Use the factor theorem: if (x - a) is a factor, then f(a) = 0. Test x = 4: f(4) = 64 - 64 + 4 - 4 = 0 ✓. Therefore, (x - 4) is a factor. You can verify by factoring: x³ - 4x² + x - 4 = x²(x - 4) + 1(x - 4) = (x² + 1)(x - 4).",
    },
    {
        "question_id": "hard_math_002",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Geometry and Trigonometry",
        "skill": "Right triangles and trigonometry",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "In a right triangle, one leg has length 5 and the hypotenuse has length 13. What is the area of the triangle?",
        "choice_a": "24",
        "choice_b": "30",
        "choice_c": "32.5",
        "choice_d": "60",
        "correct_answer": "B",
        "explanation": "Use the Pythagorean theorem to find the other leg: a² + 5² = 13² → a² + 25 = 169 → a² = 144 → a = 12. This is a 5-12-13 right triangle. Area = (1/2) × base × height = (1/2) × 5 × 12 = 30.",
    },
    {
        "question_id": "hard_math_003",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Nonlinear functions",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "The function g is defined by g(x) = 2^(x-1) - 8. For what value of x does g(x) = 0?",
        "choice_a": "2",
        "choice_b": "3",
        "choice_c": "4",
        "choice_d": "5",
        "correct_answer": "C",
        "explanation": "Set g(x) = 0: 2^(x-1) - 8 = 0 → 2^(x-1) = 8. Since 8 = 2³, we have 2^(x-1) = 2³. Therefore, x - 1 = 3, and x = 4. Verify: g(4) = 2^(4-1) - 8 = 2³ - 8 = 8 - 8 = 0 ✓",
    },
    {
        "question_id": "hard_math_004",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Problem-Solving and Data Analysis",
        "skill": "Probability and conditional probability",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "A dataset has a mean of 50 and a standard deviation of 10. If each value in the dataset is multiplied by 2 and then 5 is added, what is the new mean?",
        "choice_a": "55",
        "choice_b": "100",
        "choice_c": "105",
        "choice_d": "110",
        "correct_answer": "C",
        "explanation": "When transforming data by y = ax + b: new mean = a(old mean) + b. Here, a = 2 and b = 5. New mean = 2(50) + 5 = 100 + 5 = 105. Note: The standard deviation would become 2 × 10 = 20 (only affected by multiplication, not addition).",
    },
    {
        "question_id": "hard_math_005",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Nonlinear equations in one variable and systems of equations in two variables",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "If p(x) = x³ - 6x² + 11x - 6, and p(1) = 0, p(2) = 0, and p(3) = 0, what is the sum of all coefficients of p(x)?",
        "choice_a": "-6",
        "choice_b": "0",
        "choice_c": "1",
        "choice_d": "6",
        "correct_answer": "B",
        "explanation": "The sum of coefficients equals p(1). We're told p(1) = 0, so the sum is 0. Alternatively, add coefficients: 1 + (-6) + 11 + (-6) = 0. This polynomial factors as (x-1)(x-2)(x-3).",
    },
    {
        "question_id": "hard_math_006",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Geometry and Trigonometry",
        "skill": "Circles",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "A circle has a circumference of 16π. What is the area of a sector of this circle with a central angle of 90°?",
        "choice_a": "4π",
        "choice_b": "8π",
        "choice_c": "16π",
        "choice_d": "64π",
        "correct_answer": "C",
        "explanation": "First, find the radius: C = 2πr = 16π, so r = 8. The full circle's area = πr² = π(64) = 64π. A 90° sector is 90/360 = 1/4 of the circle. Sector area = (1/4)(64π) = 16π.",
    },
    {
        "question_id": "hard_math_007",
        "assessment": "SAT",
        "test": "Math",
        "domain": "Advanced Math",
        "skill": "Nonlinear functions",
        "difficulty": "hard",
        "question_type": "free_response",
        "question_text": "If the function f(x) = ax² + bx + c has a minimum value of -4 at x = 2, and f(0) = 0, what is the value of a?",
        "correct_answer": "1",
        "explanation": "f(0) = c = 0. The vertex is at x = -b/(2a) = 2, so b = -4a. The minimum value: f(2) = a(4) + b(2) + 0 = 4a + 2b = 4a + 2(-4a) = 4a - 8a = -4a = -4. Therefore, a = 1.",
    },
    # Hard Reading
    {
        "question_id": "hard_read_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Craft and Structure",
        "skill": "Text structure and purpose",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "passage": "Critics of artificial intelligence often invoke the specter of job displacement, painting dire pictures of mass unemployment. However, historical precedent suggests a more nuanced reality. The introduction of automated looms in the 19th century initially displaced textile workers, yet ultimately created more jobs in manufacturing, maintenance, and new industries than it eliminated. The question is not whether AI will change the job market—it undoubtedly will—but whether we can adapt our education systems and social policies quickly enough to help workers transition to new roles.",
        "question_text": "The author mentions automated looms primarily to:",
        "choice_a": "argue that all technological change is beneficial",
        "choice_b": "demonstrate that historical patterns may inform current debates",
        "choice_c": "suggest that AI will definitely create more jobs",
        "choice_d": "criticize the textile industry's treatment of workers",
        "correct_answer": "B",
        "explanation": "The author uses the historical example to show a 'more nuanced reality' than simple job displacement fears. The example demonstrates how past technological disruption eventually created more opportunities—suggesting history can inform (not definitively predict) current AI debates.",
    },
    {
        "question_id": "hard_read_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Information and Ideas",
        "skill": "Inferences",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "passage": "The octopus possesses a remarkably decentralized nervous system, with approximately two-thirds of its neurons located in its arms rather than its central brain. Each arm can independently sense and react to stimuli, solve simple problems, and even continue functioning for a short time if severed. This distributed intelligence challenges our traditional understanding of cognition as necessarily centralized.",
        "question_text": "Based on the passage, which statement can most reasonably be inferred?",
        "choice_a": "Octopuses are more intelligent than mammals",
        "choice_b": "Intelligence may take forms different from human cognition",
        "choice_c": "All invertebrates have decentralized nervous systems",
        "choice_d": "Severed octopus arms can live indefinitely",
        "correct_answer": "B",
        "explanation": "The passage states this system 'challenges our traditional understanding of cognition as necessarily centralized.' This implies intelligence can exist in non-centralized forms—different from human cognition. The passage doesn't compare octopus to mammal intelligence (A), generalize to all invertebrates (C), or claim indefinite survival (D).",
    },
    {
        "question_id": "hard_read_003",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Craft and Structure",
        "skill": "Cross-text connections",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "passage": "Text 1: Recent studies suggest that multitasking—performing multiple tasks simultaneously—actually decreases overall productivity. When the brain switches between tasks, it requires time to refocus, leading to cumulative time loss and increased errors.\n\nText 2: While continuous task-switching may indeed reduce efficiency, strategic multitasking during low-cognitive-demand activities can be beneficial. Listening to educational podcasts while exercising, for instance, allows productive use of time without significant cognitive costs.",
        "question_text": "How would the author of Text 2 most likely respond to the claim in Text 1?",
        "choice_a": "By completely rejecting the research cited in Text 1",
        "choice_b": "By acknowledging the research while noting context-dependent exceptions",
        "choice_c": "By arguing that all multitasking is beneficial",
        "choice_d": "By questioning the definition of productivity used in the studies",
        "correct_answer": "B",
        "explanation": "Text 2 acknowledges that 'continuous task-switching may indeed reduce efficiency' (agreeing with Text 1's premise) but then identifies exceptions for 'low-cognitive-demand activities.' This represents acknowledging research while noting context-dependent limitations.",
    },
    # Hard Writing
    {
        "question_id": "hard_write_001",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical synthesis",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "A student is writing an argumentative essay about renewable energy. Which sentence would best serve as a topic sentence for a paragraph discussing economic benefits?",
        "choice_a": "Renewable energy sources like solar and wind have become increasingly popular.",
        "choice_b": "Beyond environmental advantages, renewable energy investments generate significant economic returns through job creation and reduced energy costs.",
        "choice_c": "Many people believe renewable energy is the future.",
        "choice_d": "The history of solar panels dates back to the 1950s.",
        "correct_answer": "B",
        "explanation": "A strong topic sentence should clearly state the paragraph's main idea. Option B directly introduces economic benefits (job creation, reduced costs) as the focus. A is too general, C is vague, and D discusses history rather than economic benefits.",
    },
    {
        "question_id": "hard_write_002",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Standard English Conventions",
        "skill": "Boundaries",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": 'Which version correctly combines these two sentences? "The experiment failed to produce the expected results. The researchers published their findings anyway."',
        "choice_a": "The experiment failed to produce the expected results, the researchers published their findings anyway.",
        "choice_b": "The experiment failed to produce the expected results; however, the researchers published their findings anyway.",
        "choice_c": "The experiment failed to produce the expected results however the researchers published their findings anyway.",
        "choice_d": "The experiment failing to produce the expected results, the researchers published their findings anyway.",
        "correct_answer": "B",
        "explanation": "Option B correctly uses a semicolon before the conjunctive adverb 'however' and a comma after it. Option A is a comma splice (two independent clauses joined only by a comma). Option C lacks necessary punctuation. Option D creates a dangling modifier.",
    },
    {
        "question_id": "hard_write_003",
        "assessment": "SAT",
        "test": "Reading and Writing",
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "hard",
        "question_type": "multiple_choice",
        "question_text": "Which choice most effectively sets up the information that follows?\n\n_____ the architectural design of the new museum has received widespread acclaim, some critics argue that its location in a flood-prone area poses significant long-term risks.",
        "choice_a": "Because",
        "choice_b": "Although",
        "choice_c": "Therefore",
        "choice_d": "Furthermore",
        "correct_answer": "B",
        "explanation": "'Although' sets up a concession/contrast: the design is praised, BUT there are concerns about location. 'Because' implies causation (wrong relationship), 'Therefore' implies conclusion (doesn't fit), and 'Furthermore' implies addition without the contrast the sentence requires.",
    },
]


class Command(BaseCommand):
    help = "Import SAT questions with all difficulty levels (easy, medium, hard)"

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for q_data in QUESTIONS_DATA:
            question, created = Question.objects.update_or_create(question_id=q_data["question_id"], defaults=q_data)

            if created:
                created_count += 1
                self.stdout.write(f"  Created: {question.question_id}")
            else:
                updated_count += 1
                self.stdout.write(f"  Updated: {question.question_id}")

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSuccessfully imported {created_count} new questions, updated {updated_count} existing questions."
            )
        )

        # Summary by difficulty
        easy_count = sum(1 for q in QUESTIONS_DATA if q["difficulty"] == "easy")
        medium_count = sum(1 for q in QUESTIONS_DATA if q["difficulty"] == "medium")
        hard_count = sum(1 for q in QUESTIONS_DATA if q["difficulty"] == "hard")

        self.stdout.write("\nQuestion distribution:")
        self.stdout.write(f"  Easy: {easy_count}")
        self.stdout.write(f"  Medium: {medium_count}")
        self.stdout.write(f"  Hard: {hard_count}")
