# Generated by Django 5.2.10 on 2026-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text="Unique College Board question identifier (e.g., '3d1070c9')", max_length=20, unique=True)),
                ('assessment', models.CharField(choices=[('SAT', 'SAT'), ('PSAT', 'PSAT/NMSQT')], default='SAT', max_length=10)),
                ('test', models.CharField(choices=[('Math', 'Math'), ('Reading and Writing', 'Reading and Writing')], max_length=50)),
                ('domain', models.CharField(choices=[('Algebra', 'Algebra'), ('Advanced Math', 'Advanced Math'), ('Problem-Solving and Data Analysis', 'Problem-Solving and Data Analysis'), ('Geometry and Trigonometry', 'Geometry and Trigonometry'), ('Information and Ideas', 'Information and Ideas'), ('Craft and Structure', 'Craft and Structure'), ('Expression of Ideas', 'Expression of Ideas'), ('Standard English Conventions', 'Standard English Conventions')], max_length=100)),
                ('skill', models.CharField(help_text="Specific skill being tested (e.g., 'Linear functions')", max_length=150)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('free_response', 'Free Response')], default='multiple_choice', max_length=20)),
                ('passage', models.TextField(blank=True, help_text='Optional passage or context for the question', null=True)),
                ('question_text', models.TextField(help_text='The actual question text (may contain LaTeX math expressions)')),
                ('choice_a', models.TextField(blank=True, null=True)),
                ('choice_b', models.TextField(blank=True, null=True)),
                ('choice_c', models.TextField(blank=True, null=True)),
                ('choice_d', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(help_text="Correct answer: 'A', 'B', 'C', 'D' for MC, or numeric value for free response", max_length=100)),
                ('explanation', models.TextField(help_text='Detailed rationale explaining the correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'skill', 'difficulty'],
                'indexes': [models.Index(fields=['test', 'domain'], name='questions_q_test_a220b5_idx'), models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx'), models.Index(fields=['skill'], name='questions_q_skill_28f898_idx')],
            },
        ),
    ]
