# Generated by Django 5.2.10 on 2026-01-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionattempt_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(help_text="Skill identifier (e.g., 'ALG-1')", max_length=10, unique=True)),
                ('domain', models.CharField(choices=[('Algebra', 'Algebra'), ('Advanced Math', 'Advanced Math'), ('Problem-Solving and Data Analysis', 'Problem-Solving and Data Analysis'), ('Geometry and Trigonometry', 'Geometry and Trigonometry')], max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within domain')),
            ],
            options={
                'verbose_name': 'Math Skill',
                'verbose_name_plural': 'Math Skills',
                'ordering': ['domain', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['domain', 'skill_name', 'difficulty']},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_skill_28f898_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='skill',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('college_board', 'College Board'), ('custom', 'Custom')], default='college_board', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(help_text="Unique question identifier (e.g., 'ALG-E-001')", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='skill_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to the official skill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.skill'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['skill_name'], name='questions_q_skill_n_ba597c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source'], name='questions_q_source_1db740_idx'),
        ),
    ]
