# Generated by Django 5.2.10 on 2026-01-28 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_add_skill_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('mini', 'Mini Test'), ('section', 'Section Test'), ('full', 'Full Practice')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('user_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='questions.testsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', 'status'], name='questions_t_user_id_6c8ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', 'started_at'], name='questions_t_user_id_e04bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='testsessionquestion',
            index=models.Index(fields=['session', 'order'], name='questions_t_session_7b7961_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testsessionquestion',
            unique_together={('session', 'order')},
        ),
    ]
