# Generated by Django 5.2.10 on 2026-01-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_test_session_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Points earned from this test'),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('tests_completed', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive days practiced')),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('weekly_points', models.PositiveIntegerField(default=0, help_text='Points earned this week')),
                ('week_start', models.DateField(blank=True, help_text='Start of current tracking week', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['-total_points'], name='questions_u_total_p_040d67_idx'), models.Index(fields=['-weekly_points'], name='questions_u_weekly__62393c_idx')],
            },
        ),
    ]
