# Generated by Django 5.2.10 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_add_user_stats_and_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='month_start',
            field=models.DateField(blank=True, help_text='Start of current tracking month', null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='monthly_points',
            field=models.PositiveIntegerField(default=0, help_text='Points earned this month'),
        ),
    ]
