# Generated by Django 5.2.10 on 2026-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_add_visualization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
